[gpg]
pubkey_url = "https://github.com/xbersoy.gpg"
fingerprint = "CD9BBE28A8A361890CE259FBED10AA39"

[git.init]
default_branch = "master"

[git.user]
name = "Burak Ersoy"
email = "burakersoy@msn.com"
signing_key = "CD9BBE28A8A361890CE259FBED10AA39"

[git.commit]
gpgsign = "false"

[prefs]
editor = "nvim"
visual = "nvim"
dracula_pro = false
dracula_pro_url = "https://github.com/krmbzds/dracula-pro"

[fonts]
antialiasing = true
antialiasing_type = "subpixel"
hinting = true
hintstyle = "hintslight"
lcdfilter = "lcddefault"
font_mscore = true
font_croscore = true
font_crosextra = true
font_source_code_pro = true

[dependencies]
anki = false
zeal = false
faas = false
meld = false
brave = false
broot = false
geary = false
totem = false
docker = true
evince = false
zathura = false
flatpak = true
newsboat = false
brave_beta = false
difftastic = false
whispercpp = false
libreoffice = false
taskwarrior = false
sublime_text = false
simple_scanner = false
signal_messenger = false

[gnome]
dracula = false
enable_animations = false
logout_prompt = false
natural_scroll = true
static_workspaces = true
workspace_count = 2

[gnome.desktop]
icons = false
clock_format = '24h'
show_date = true
show_seconds = false
show_weekday = true

[gnome.mutter]
center_new_windows = true
center_window = "<Super>c"

[gnome.dash_to_dock]
autohide = true
position  = "LEFT"

[asdf]
enabled = true
lua = true
ruby = true
rust = true
yarn = true
golang = true
nodejs = true
python = true
postgres = true
fd = true
xh = true
bat = true
duf = true
exa = true
dust = true
helm = true
tmux = true
vale = true
cheat = true
delta = true
doctl = false
viddy = true
direnv = true
neovim = true
stylua = true
kubectl = false
lazygit = true
ripgrep = true
terraform = false
lazydocker = true
shellcheck = true
github_cli = true

[hardware.huawei.gxtp7863.touchpad]
enabled = true
scrolling_pixel_distance = 50
